import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#b61722",
        "on-primary": "#ffffff",
        "primary-container": "#da3437",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdad7",
        "primary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#410004",
        "on-primary-fixed-variant": "#930013",
        "inverse-primary": "#ffb3ad",
        "surface-tint": "#b91a24",
        "secondary": "#575e70",
        "on-secondary": "#ffffff",
        "secondary-container": "#d9dff5",
        "on-secondary-container": "#5c6274",
        "secondary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#c0c6db",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        "tertiary": "#006765",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008280",
        "on-tertiary-container": "#f3fffd",
        "tertiary-fixed": "#87f4f0",
        "tertiary-fixed-dim": "#69d8d4",
        "on-tertiary-fixed": "#00201f",
        "on-tertiary-fixed-variant": "#00504e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9f6",
        "on-background": "#1a1c1b",
        "surface": "#f9f9f6",
        "surface-dim": "#dadad7",
        "surface-bright": "#f9f9f6",
        "surface-variant": "#e2e3e0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f1",
        "surface-container": "#eeeeeb",
        "surface-container-high": "#e8e8e5",
        "surface-container-highest": "#e2e3e0",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#5b403e",
        "inverse-surface": "#2f312f",
        "inverse-on-surface": "#f1f1ee",
        "outline": "#8f6f6d",
        "outline-variant": "#e4beba",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-mobile": "20px",
        "margin-desktop": "40px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "stack-sm": "8px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "display": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "label-caps": ["var(--font-inter)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
